[project]
name = "grad-assist"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.15.0",
    "langchain>=1.3.14",
    "langchain-openai>=1.3.5",
    "langgraph>=1.2.9",
    "minio>=7.2.20",
    "pymilvus>=3.0.0",
    "pypdf>=6.14.2",
    "python-dotenv>=1.2.2",
    "requests>=2.31.0",

    # PyTorch CUDA 版本
    "torch>=2.7",
    # BGE-M3 嵌入模型
    "FlagEmbedding",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]

# 指定 PyTorch CUDA 12.8 软件源
[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

# 强制 PyTorch 相关依赖从 CUDA 软件源安装
[tool.uv.sources]
torch = { index = "pytorch-cu128" }